// import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";   
import "./globals.css";
import Link from "next/link";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="min-h-screen bg-gradient-to-br from-blue-50 via-purple-50 to-pink-50">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${inter.className} min-h-screen`}
      >
        <nav className="mx-auto mt-6 mb-8 max-w-4xl rounded-2xl shadow-lg bg-gradient-to-r from-blue-600 via-purple-600 to-pink-500 p-4">
          <ul className="flex justify-center gap-8">
            <li>
              <Link href="/" 
                    className="text-white font-bold px-4 py-2 rounded-lg transition-colors duration-200 hover:bg-white/20 hover:text-yellow-300">Home</Link>
            </li>
            <li>
              <Link href="/about" 
                    className="text-white font-bold px-4 py-2 rounded-lg transition-colors duration-200 hover:bg-white/20 hover:text-yellow-300">About</Link>
            </li>
            <li>
              <Link href="/careers" 
                    className="text-white font-bold px-4 py-2 rounded-lg transition-colors duration-200 hover:bg-white/20 hover:text-yellow-300">Career</Link>
            </li>
            <li>
              <Link href="/blogs" 
                    className="text-white font-bold px-4 py-2 rounded-lg transition-colors duration-200 hover:bg-white/20 hover:text-yellow-300">Blogs</Link>
            </li>
            <li>
              <Link href="/posts" 
                    className="text-white font-bold px-4 py-2 rounded-lg transition-colors duration-200 hover:bg-white/20 hover:text-yellow-300">Posts</Link>
            </li>
            <li>
              <Link href="/contact" 
                    className="text-white font-bold px-4 py-2 rounded-lg transition-colors duration-200 hover:bg-white/20 hover:text-yellow-300">Contact Us</Link>
            </li>
          </ul>
        </nav>
        <div className="mx-auto max-w-3xl bg-white/80 rounded-xl shadow p-8">
          {children}
        </div>
      </body>
    </html>
  );
}
